# Generated by Django 2.2.7 on 2019-11-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191116_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=2, verbose_name='Язык'),
        ),
    ]
