version: '3.7'


services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    rabbitmq:
        image: "rabbitmq:3-management"
        hostname: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=xxx
            - RABBITMQ_DEFAULT_PASS=xxx
        ports:
            - "5672:5672"
            - "15672:15672"
        labels:
            NAME: "rabbitmq"
        volumes:
            - "rabbitmq_data:/data"

volumes:
    postgres_data:
    rabbitmq_data: