# Generated by Django 2.2.7 on 2019-11-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-add_date'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
    ]
